Remove extra google cloud sdk files and handle vars.

diff --git a/script/env b/script/env
--- a/script/env
+++ b/script/env
@@ -1,6 +1,15 @@
 #!/bin/bash
 
-# set environment vars from project defaults
+if  [ -n "GCLOUD_CREDENTIALS" ]; then
+    echo "GCLOUD_CREDENTIALS not set, this is required to push and deploy successfully"
+    exit 1
+fi
 
-# get name from cloned project
-# get commitsh from project
+#testing
+export DRY_RUN="yes"
+export REGISTRY_URL=${REGISTRY_URL:-gcr.io/celo-testnet}
+
+# github compatibility
+export NAME=$(cut -d "/" -f2 <<< $GITHUB_REPOSITORY)
+export COMMITSH=${COMMITSH:-GITHUB_SHA}
+export RELEASE_NAME="${ENVIRONMENT}-${NAME}"
